
sudo: required


services:
  - docker


before_install:
  - docker build -t chinedunnanna/react_application -f Dockerfile.dev .


script:
  - docker run chinedunnanna/react_application npm run test -- --coverage