
sudo: required


services:
  - docker


before_install:
  - docker build -t chinedunnanna/react_application -f Dockerfile.dev .


script:
  - docker run -p 3000:3000 chinedunnanna/react_application 